### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by kimkong88** [bhargavms/DotLoader#8]
> FATAL EXCEPTION: main
                                                                                 Process: com.example.dkim.starbucksecret, PID: 21165
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.ValueAnimator.start()' on a null object reference
                                                                                     at com.bhargavms.dotloader.DotLoader._startAnimation(DotLoader.java:219)
                                                                                     at com.bhargavms.dotloader.DotLoader.access$200(DotLoader.java:21)
                                                                                     at com.bhargavms.dotloader.DotLoader$2.run(DotLoader.java:196)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

> 

weird I am getting this.

It was working fine then It just started to happen today.

Just updated Android Studio and Compile SDK to the latest version but I am not sure if its related.

The error does not happen in other activity/fragment. only this specific activity I am getting this error.

Dotloader is set up exactly same way as it is setup in other activity.

**Comment by kimkong88** [comment]
please disregard this. Problem is fixed when I updated DotLoader to the newest version
